### PR TITLE
add mpe mode

### PR DESCRIPTION
**Pull request by scazan**
hey, I was using the MollyThePoly engine in a script I was making and realized it was basically setup for MPE compatibility with some minor changes so here is a PR of the changes I made if you think it's useful for others.

since note_num was used as an ID on the SC side I just switched to using channel number in MPE mode instead.
tested with a seaboard block only however at this time.

### CODE REVIEW

**Comment by scazan** [comment]
and now I just saw your comment on MPE in the lines post! :) thanks again for such a nice norns synth.

**Comment by markwheeler** [comment]
Thx for this! Will probably be a few days before I can give it a look over but look forward to getting this added in.

**Comment by markwheeler** [comment]
Sorry for the slow pace. Merged in now, thank you! You may be interested in checking out the [vNext branch](https://github.com/markwheeler/molly_the_poly/tree/vNext) where I started adding a lot more per voice modulation in the engine with MPE in mind. I'm afraid I left it somewhat unfinished though 😬

**Comment by scazan** [comment]
no worries and thanks! I'll definitely try to run the vNext branch!

**Pull request merged**
